# Generated by Django 4.1.2 on 2022-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.CharField(max_length=128, verbose_name='Image')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(verbose_name='URL')),
            ],
        ),
    ]
